import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    home: "Accueil", finances: "Finances", members: "Membres", settings: "Réglages", profile: "Profil",
    welcome_message: "Bonjour",
    welcome_subtitle: "Voici votre synthèse du jour: cotisations, tour en cours et prochaines actions.",
    beneficiary_banner_title: "Vous êtes le bénéficiaire du mois !",
    beneficiary_banner_received: "envoyés", beneficiary_banner_waiting: "vous seront envoyés",
    update_data: "Actualiser les données", active_cycle: "Cycle actif", current_tour: "Tour",
    next_beneficiary: "Prochain bénéficiaire", total_pool: "Montant total de la cagnotte",
    cycle_progression: "Progression du cycle",
    pay_cotisation_wave: "Payer ma cotisation (Wave)", pay_cotisation_orange: "Payer (Orange Money)",
    target_cotisation: "Cotisation cible", amount_contributed: "Montant cotisé",
    next_tour: "Prochain tour", estimated_order: "Ordre prévisionnel",
    sign_for_payout: "Signer pour Décaissement", confirm_payout_msg: "Valider votre signature",
    signed_payout: "Signature enregistrée", make_loan_request: "Faire une demande de prêt",
    recent_activity: "Vos dernières opérations", no_recent_activity: "Aucune opération récente pour le moment.",
    cotisation: "Cotisation", penalty: "Pénalité", loan: "Prêt", draw: "Tirage",
    loading: "Chargement...", refreshing: "Mise à jour...",
    financial_performance: "Performance financière", real_time: "Temps réel",
    dashboard_overview: "Vue d'ensemble", loans: "Prêts",
    finance_intro: "Suivez les indicateurs clés, contrôlez les flux et exportez vos rapports.",
    cotisations_today: "Cotisations aujourd'hui", pending_penalties: "Pénalités en cours",
    active_loans: "Prêts actifs", top_contributors: "Membres les plus contributeurs",
    cycle_summary: "Résumé du cycle", total_collected: "Total collecté",
    loan_repayment_rate: "Taux cotisation", real_time_flow: "Flux d'activité en temps réel",
    latest_transactions: "Dernières transactions",
    add_member: "Ajouter un membre", start_tirage: "Lancer un tirage",
    send_reminders: "Envoyer rappels", paid_members: "Membres à jour",
    no_member_found: "Aucun membre trouvé.", apply_penalty: "Appliquer une pénalité",
    tontine_settings: "Paramètres de la Tontine", tontine_name: "Nom de la Tontine",
    save_changes: "Enregistrer",
    logout: "Déconnexion", change_language: "Changer de langue",
    dark_mode: "Mode sombre", light_mode: "Mode clair", language_select: "Sélectionnez votre langue",
    // Navigation sidebar
    nav_home: "Tableau de bord", nav_finances: "Finances", nav_members: "Membres",
    nav_tontines: "Tontines", nav_tirage: "Tirage", nav_notifications: "Notifications",
    nav_rappels: "Rappels", nav_settings: "Paramètres",
    nav_group_main: "Principal", nav_group_manage: "Gestion",
    system_active: "Système actif",
    role_admin: "Gérant · Admin",
    role_member: "Membre",
    // Topbar page titles
    page_home: "Tableau de bord", page_finances: "Finances", page_members: "Membres",
    page_tontines: "Tontines", page_notifications: "Notifications",
    page_rappels: "Envoyer un rappel", page_settings: "Paramètres",
    page_profile: "Mon Profil", page_tirage: "Tirage Mensuel",
    page_privacy: "Confidentialité", page_cgu: "CGU", page_faq: "FAQ",
    // Join tontine prompt
    no_tontine_title: "Vous n'avez pas encore rejoint de tontine",
    no_tontine_sub: "Entrez le code d'invitation de 6 caractères partagé par votre gérant.",
    no_tontine_btn: "Rejoindre une tontine",
    // LoanItem
    loan_status_pending: "En attente", loan_status_approved: "Approuvé", loan_status_current: "En cours", loan_status_repaid: "Remboursé", loan_status_rejected: "Rejeté",
    loan_cancel: "Annuler", loan_processing: "Traitement...", loan_confirm_reject: "Confirmer le rejet", loan_confirm_signature: "Confirmer la signature",
    loan_member: "Membre", loan_no_motif: "Aucun motif", loan_already_signed: "✓ Déjà signé", loan_sign_step1: "✍ Signer (1/2)", loan_sign_step2: "✍ Confirmer (2/2)",
    loan_reject_btn: "Rejeter", loan_capital: "Capital", loan_total_interests: "Total avec intérêts (10%)", loan_rejected_title: "Demande rejetée",
    loan_rejected_msg: "Cette demande de prêt a été refusée par les gérants.", loan_pending_title: "En attente de validation",
    loan_pending_msg: "2 signatures de gérants requises ({count}/2 reçues)", loan_loading_schedule: "Chargement de l'échéancier...",
    loan_schedule_title: "Échéancier de remboursement", loan_paid: "PAYÉ", loan_to_pay: "À PAYER", loan_collect_btn: "Encaisser",
    loan_balance_due: "Solde restant dû", loan_collect_amount: "Encaisser {amount} F", loan_confirm_collect: "Confirmer l'encaissement de l'échéance de {amount} F ?",
    // SpinWheel
    spin_winner_congrats: "🎉 Félicitations {name} ! Vous avez été tiré(e) au sort pour le tour de {month} de la Tontine Nataal. Montant : {amount} FCFA. Contactez l'administrateur pour le versement. Bonne chance ! 🤝",
    spin_winner_label: "Bénéficiaire du tirage", spin_amount_month: "Montant — {month}", spin_send_sms: "📱 Envoyer un SMS",
    spin_no_phone: "Aucun numéro de téléphone enregistré", spin_close: "Fermer", spin_spinning: "La roue tourne…",
    spin_launch: "Lancer la roue !", spin_eligible_count: "{count} participant{s} éligible{s}",
    // Logout confirmation
    logout_confirm_title: "Se déconnecter ?",
    logout_confirm_msg: "Vous serez redirigé vers la page de connexion.",
    logout_confirm_yes: "Se déconnecter",
    logout_confirm_no: "Annuler",
    // Finances filters
    all: "Tous", pending: "En attente", approved: "Approuvé", repaid: "Remboursé", rejected: "Rejeté",
    export: "Exporter",
    // Profile
    edit_profile: "Modifier le profil", change_password: "Changer le mot de passe",
    // Tontines
    all_tontines: "Toutes les tontines", invite_code: "Code d'invitation", copy: "Copier", join: "Rejoindre", evaluation: "Évaluation",
    status: "Statut", progression: "Progression",
    tontine_intro_gerant: "Configuration, rejoindre ou évaluation.",
    tontine_intro_membre: "Rejoindre une tontine ou voir l'évaluation.",
    copy_success: "Code copié.", invite_code_sub: "Partage ce code (6 caractères) pour inviter un membre.",
    available_tontines: "Tontines Disponibles", share_with_members: "À partager avec les membres",
    // Landing Page
    landing_hero_badge: "Système de gestion nouvelle génération",
    landing_hero_title: "Pilotez votre Tontine avec une clarté absolue.",
    landing_hero_sub: "La solution premium pour gérer vos cotisations, tours de table et prêts. Simplifiez votre épargne collective avec une interface professionnelle et transparente.",
    landing_cta_start: "Démarrer maintenant",
    landing_cta_view: "Voir ma tontine",
    landing_cta_note: "Déjà plus de 500 membres actifs au Sénégal.",
    landing_divider_text: "Excellence & Confiance",
    landing_features_label: "Nos piliers",
    landing_feat1_title: "Sécurité Totale",
    landing_feat1_text: "Vos fonds et données sont protégés par un cryptage de bout en bout et un système de validation multicritère.",
    landing_feat2_title: "Tirage Aléatoire",
    landing_feat2_text: "Un algorithme transparent et équitable pour désigner les bénéficiaires mensuels en direct.",
    landing_feat3_title: "Prêts Facilités",
    landing_feat3_text: "Accédez à des solutions de crédit internes avec une validation rapide par les gérants de la tontine.",
    landing_stats_label: "En quelques chiffres",
    landing_stat1_label: "CFA Collectés mensuellement",
    landing_stat2_label: "Taux de remboursement",
    landing_stat3_label: "Accès au tableau de bord",
    landing_footer_copy: "© 2026 Nataal Group. Tous droits réservés.",
    // Auth
    login_title: "Connexion",
    login_subtitle: "Accédez à votre espace Tontine Nataal",
    login_email_label: "Email Professionnel",
    login_pass_label: "Mot de passe",
    login_btn: "Se connecter",
    login_loading: "Connexion...",
    login_no_account: "Pas encore membre ?",
    login_create_account: "Créer un compte",
    register_title: "Inscription",
    register_subtitle: "Créez votre compte Tontine Nataal",
    register_name_label: "Nom Complet",
    register_btn: "Créer mon compte",
    register_loading: "Création...",
    register_already_member: "Déjà membre ?",
    back: "Retour",
    // Dashboard missing
    per_member_month: "Par membre / mois",
    total_personal: "Total personnel",
    global_progress: "Avancement global",
    recent_activity_log: "Journal d’activité récent",
    loan_rate: "Taux de paiement global",
    all_read: "Tout lire",
    unread: "Non lues",
    // Supplementary
    members_list: "Liste des membres",
    paid: "Payé",
    edit: "Éditer",
    confirm_action: "Confirmer l'action",
    old_password: "Ancien mot de passe",
    new_password: "Nouveau mot de passe",
    validate_change: "Valider le changement",
    turn: "Tour",
    fill_all_fields: "Veuillez remplir tous les champs",
    saving: "Sauvegarde...",
    photo: "Photo",
    remove_photo: "Retirer la photo",
    tirage_title: "Tirage Mensuel",
    cycle_in_progress: "Cycle en cours",
    members_served: "membres servis",
    no_security_log: "Aucun journal de sécurité enregistré",
    audit_title: "Journal d'Audit & Sécurité",
    loading_history: "Chargement de l'historique...",
    user: "Utilisateur",
    details: "Détails",
    amount: "Montant",
    invalid_amount: "Veuillez saisir un montant valide",
    tirage_confirm_msg: "Lancer le tirage du mois ?",
    payout_confirm_msg: "Confirmer l'envoi de l'argent ?",
    irreversible_action: "Cette action est irréversible.",
    all_beneficiaries_served: "Tous les membres ont bénéficié ! Nouveau cycle à venir.",
    payment_method: "Méthode de paiement",
    payment_success_title: "Paiement validé !",
    payment_success_msg: "Votre cotisation a été enregistrée avec succès.",
    loan_request_title: "Demande envoyée !",
    loan_request_msg: "Les gérants examineront votre demande prochainement.",
    close: "Fermer",
    reason: "Motif",
    processing: "Traitement...",
    new_member: "Nouveau membre",
    edit_member: "Édition membre",
    delete_member_title: "Supprimer ce membre ?",
    delete_member_msg: "Cette action est irréversible. Les données seront définitivement effacées.",
    send_email_to: "Email à",
    email_subject: "Sujet de l'email",
    message: "Message",
    send_now: "Envoyer l'email maintenant",
    mandatory_fields: "Nom, email et mot de passe sont obligatoires",
    photo_too_large: "Photo trop lourde (max 3 MB)",
    invite_code_label: "Code d'invitation",
    join_success: "Rejoint avec succès.",
    invalid_code: "Code invalide.",
    tontine_progression: "Progression",
    total_pot: "Cagnotte totale",
    frequency: "Fréquence",
    max_members: "Membres max",
    management_fees: "Frais gestion",
    summary: "RÉCAPITULATIF",
    start_date: "Date de début",
    num_places: "Nb de places",
    fill_all_fields: "Veuillez remplir tous les champs",
    disbursement: "Décaissement",
    confirm_reminder_all: "Envoyer un email de rappel à tous les membres en attente de paiement ?",
    tontine_name_placeholder: "Ex: Tontine des amis",
    tontine_desc_placeholder: "Décrivez votre tontine...",
    tontine_intro_gerant: "Configuration, rejoindre ou évaluation.",
    tontine_intro_membre: "Rejoindre une tontine ou voir l'évaluation.",
    copy_success: "Code copié.",
    copy: "Copier",
    invite_code: "Code d'invitation",
    invite_code_sub: "Partage ce code (6 caractères) pour inviter un membre.",
    join: "Rejoindre",
    error_occurred: "Une erreur est survenue",
    refresh: "Rafraîchir",
    status_received: "Reçu",
    status_pending: "En attente",
    tirage_congrats: "Félicitations {name} ! Vous avez été tiré(e) au sort pour le tour de {month}. Cagnotte : {amount} FCFA.",
    tirage_modal_title: "Tirage au sort - ",
    tirage_no_eligible_title: "Aucun membre éligible",
    tirage_no_eligible_msg: "Tous les membres à jour de cotisation pour ce tour ont déjà bénéficié d'un tirage.",
    sign_payout_1: "Confirmer le versement de {amount} F à {name} ? (Signature 1/2)",
    sign_payout_2: "Confirmer le versement final (Signature 2/2) ?",
    reminder_default_msg: "Ceci est un rappel pour votre cotisation Nataal. Merci de régulariser votre situation.",
    beneficiary_banner_title: "Vous êtes le bénéficiaire du mois !",
    amount_sent: "envoyés",
    amount_will_be_sent: "vous seront envoyés",
    status_received: "REÇU",
    status_pending: "EN ATTENTE",
    sign_payout_1: "Valider votre signature (1/2) pour décaisser {amount} F pour {name} ?",
    sign_payout_2: "Confirmer la signature finale (2/2) et clôturer ce tour ?",
    // TiragePage
    tirage_current_month: "TIRAGE DU MOIS EN COURS",
    tirage_beneficiary_selected: "Bénéficiaire sélectionné",
    tirage_amount: "Montant",
    tirage_confirm_send: "Confirmer l'envoi d'argent",
    tirage_sending: "Envoi en cours...",
    tirage_sent_on: "Argent envoyé le",
    tirage_new_month: "NOUVEAU TIRAGE DU MOIS",
    tirage_amount_label: "MONTANT À ENVOYER (F CFA)",
    tirage_info: "Le système sélectionnera un participant aléatoire n'ayant pas encore bénéficié.",
    reminder_default_msg: "⚠️ Rappel: votre cotisation est en attente. Merci de régulariser dès que possible.",
    faq_title: "Foire Aux Questions",
    faq_q1: "Comment rejoindre une tontine ?",
    faq_a1: "Utilisez le code à 6 chiffres partagé par votre gérant dans la section 'Rejoindre'.",
    faq_q2: "Comment se passe le tirage ?",
    faq_a2: "Le tirage est effectué aléatoirement par le système parmi les membres ayant cotisé.",
    faq_q3: "Est-ce sécurisé ?",
    faq_a3: "Oui, toutes les transactions et données sont chiffrées et protégées.",
    tirage_launching: "Tirage en cours...",
    tirage_launch_btn: "Lancer le tirage du mois",
    tirage_history: "HISTORIQUE DES TIRAGES",
    tirage_sent_status: "✓ Envoyé",
    tirage_waiting_status: "⏳ En attente",
    // SettingsPage
    settings_new_pool: "Nouvelle cagnotte",
    settings_title_label: "Titre",
    settings_description_label: "Description",
    settings_description_optional: "(Optionnel)",
    settings_amount_per_place: "Montant par place",
    settings_frequency_label: "Fréquence",
    settings_fees_label: "Frais gestion",
    settings_freq_monthly: "Par mois",
    settings_freq_weekly: "Par semaine",
    settings_freq_daily: "Par jour",
    settings_nb_places: "Nb de places",
    settings_start_date: "Date de début",
    settings_total_pool: "Cagnotte totale",
    settings_saving: "Enregistrement...",
    settings_saved: "✅ Enregistré !",
    settings_save_btn: "Enregistrer les modifications",
    settings_title_required: "Le titre est obligatoire",
    settings_freq_value_monthly: "Mensuelle",
    settings_freq_value_weekly: "Hebdo",
    settings_freq_value_daily: "Quotidienne",
    // Notifications
    notif_center: "Centre de notifications",
    notif_elements: "élément(s)",
    notif_unread: "Non lues",
    notif_all: "Toutes",
    notif_mark_all_read: "Tout lire",
    notif_loading: "Chargement…",
    notif_empty: "Aucune notification.",
    // Reminders
    reminder_title: "Rappels de paiement",
    reminder_subtitle: "Notifications in-app pour les membres en attente",
    reminder_all: "Tous les retardataires",
    reminder_select: "Sélection précise",
    reminder_pending_members: "Membres en attente",
    reminder_message_label: "Message de rappel",
    reminder_sending: "Envoi...",
    reminder_send_btn: "Envoyer les rappels maintenant",
    // Modals
    modal_photo_label: "Photo de profil",
    modal_photo_hint: "Cliquer sur l'icône pour modifier.",
    modal_photo_remove: "✕ Retirer la photo",
    modal_photo_remove_short: "✕ Retirer",
    modal_photo_optional: "Optionnel • JPG, PNG • Max 3 MB",
    modal_nom_label: "Nom",
    modal_prenom_label: "Prénom",
    modal_email_label: "Adresse Email",
    modal_email_label_short: "Email",
    modal_email_required: "Email *",
    modal_nom_required: "Nom *",
    modal_telephone_label: "Téléphone",
    modal_password_temp: "Mot de passe provisoire *",
    modal_password_placeholder: "Mot de passe",
    modal_edit_member_title: "Édition membre",
    modal_save_changes: "Enregistrer les modifications",
    modal_saving: "Enregistrement...",
    modal_creating: "Création en cours...",
    modal_create_member_btn: "Créer le membre",
    modal_confirm_title: "Confirmation",
    modal_delete_confirm: "Supprimer ce membre ?",
    modal_delete_msg: "Cette action est irréversible. Les données de",
    modal_delete_msg2: "(transactions, tours) seront définitivement effacées.",
    modal_cancel: "Annuler",
    modal_delete_btn: "Supprimer",
    modal_deleting: "Suppression...",
    modal_loan_title: "Demander un prêt",
    modal_loan_amount_label: "Montant souhaité (F CFA)",
    modal_loan_reason_label: "Motif de la demande",
    modal_loan_warning: "Cette demande nécessite la validation de deux gérants.",
    modal_loan_submitting: "Envoi en cours...",
    modal_loan_submit_btn: "Soumettre la demande",
    modal_cotiser_confirm: "Confirmer le paiement",
    modal_cotiser_processing: "Traitement...",
    modal_password_changed: "Mot de passe modifié.",
    // Finances hardcoded
    no_data: "Aucune donnée",
    no_activity_period: "Aucune activité enregistrée pour cette période.",
    no_transaction: "Aucune transaction disponible.",
    loan_none: "Aucun prêt enregistré pour le moment",
    loan_none_filtered: "Aucun prêt",
    loan_create_request: "Créer une demande de prêt",
    loan_total_borrowed: "TOTAL EMPRUNTÉ",
    loan_pending_count: "EN ATTENTE",
    loan_repaid_count: "REMBOURSÉS",
    // MembresPage batch
    batch_selected: "membre(s) sélectionné(s) pour cotisation",
    // TontinesPage etat
    tontine_progression_label: "Progression",
    tontine_tour_label: "Tour",
    tontine_code_invalid: "Code invalide.",
    tontine_6chars: "(6 caractères)",
    // ProfilPage
    profile_click_to_modify: "Cliquer sur l'icône pour modifier.",
    email_label: "Email",
    // LandingPage divider
    landing_divider_text_inline: "Excellence & Confiance",
    email_placeholder: "votre@email.com",
    name_placeholder: "Moussa Diop",
    // ParametresPage
    password_changed_msg: "Mot de passe modifié.",
    tirage_congrats: "🏆 Félicitations {name} ! Vous êtes le gagnant du tirage {month}.",
    tirage_error: "Erreur tirage : ",
    tirage_modal_title: "🎲 Tirage — ",
    tirage_no_eligible_title: "Aucun participant éligible",
    tirage_no_eligible_msg: "Tous les membres ont déjà reçu leur tour, ou aucun n'a cotisé ce mois.",
    privacy_title: "Politique de confidentialité",
    privacy_intro: "Chez Nataal, nous accordons une importance capitale à la protection de vos données. Cette politique détaille comment nous collectons et utilisons vos informations.",
    privacy_h1: "1. Collecte des données",
    privacy_p1: "Nous collectons vos noms, emails, numéros de téléphone et historiques de transactions pour assurer le bon fonctionnement de la tontine.",
    privacy_h2: "2. Utilisation",
    privacy_p2: "Vos données sont utilisées uniquement pour la gestion des tours de tontine, des prêts et des notifications de rappel.",
    cgu_title: "Conditions Générales d'Utilisation",
    cgu_intro: "L'utilisation de Nataal implique l'acceptation pleine et entière des présentes conditions.",
    cgu_h1: "1. Engagement des membres",
    cgu_p1: "Chaque membre s'engage à cotiser à temps selon la fréquence définie par le gérant.",
    cgu_h2: "2. Pénalités",
    cgu_p2: "Tout retard peut entraîner des pénalités automatiques définies dans les paramètres de la tontine.",
    placeholder_phone: "+221 ...",
    placeholder_subject: "Objet...",
    placeholder_message: "Rédigez votre message ici...",
    placeholder_loan_reason: "Ex: Frais de scolarité, Urgence...",
    tontine_premium: "Tontine premium",
  },
  en: {
    home: "Home", finances: "Finances", members: "Members", settings: "Settings", profile: "Profile",
    welcome_message: "Hello",
    welcome_subtitle: "Here is your daily summary: contributions, current round and next actions.",
    beneficiary_banner_title: "You are the beneficiary of the month!",
    beneficiary_banner_received: "sent", beneficiary_banner_waiting: "will be sent to you",
    update_data: "Update data", active_cycle: "Active cycle", current_tour: "Round",
    next_beneficiary: "Next beneficiary", total_pool: "Total pool amount",
    cycle_progression: "Cycle progression",
    pay_cotisation_wave: "Pay my contribution (Wave)", pay_cotisation_orange: "Pay (Orange Money)",
    target_cotisation: "Target contribution", amount_contributed: "Amount contributed",
    next_tour: "Next round", estimated_order: "Estimated order",
    sign_for_payout: "Sign for Payout", confirm_payout_msg: "Validate your signature",
    signed_payout: "Signature recorded", make_loan_request: "Request a loan",
    recent_activity: "Your latest operations", no_recent_activity: "No recent activity for now.",
    cotisation: "Contribution", penalty: "Penalty", loan: "Loan", draw: "Draw",
    loading: "Loading...", refreshing: "Updating...",
    financial_performance: "Financial Performance", real_time: "Real time",
    dashboard_overview: "Overview", loans: "Loans",
    finance_intro: "Track key indicators, control flows and export your reports.",
    cotisations_today: "Contributions today", pending_penalties: "Pending penalties",
    active_loans: "Active loans", top_contributors: "Top contributors",
    cycle_summary: "Cycle summary", total_collected: "Total collected",
    loan_repayment_rate: "Contribution rate", real_time_flow: "Real-time activity flow",
    latest_transactions: "Latest transactions",
    add_member: "Add a member", start_tirage: "Start a draw",
    send_reminders: "Send reminders", paid_members: "Paid members",
    no_member_found: "No member found.", apply_penalty: "Apply penalty",
    tontine_settings: "Tontine Settings", tontine_name: "Tontine Name",
    save_changes: "Save changes",
    logout: "Logout", change_language: "Change language",
    dark_mode: "Dark mode", light_mode: "Mode clair", language_select: "Select your language",
    // Navigation sidebar
    nav_home: "Dashboard", nav_finances: "Finances", nav_members: "Members",
    nav_tontines: "Tontines", nav_tirage: "Draw", nav_notifications: "Notifications",
    nav_rappels: "Reminders", nav_settings: "Settings",
    nav_group_main: "Main", nav_group_manage: "Management",
    system_active: "System active",
    role_admin: "Manager · Admin",
    role_member: "Member",
    status_received: "Received",
    status_pending: "Pending",
    tirage_congrats: "Congratulations {name}! You have been drawn for the {month} round. Pool: {amount} FCFA.",
    tirage_modal_title: "Lucky Draw - ",
    tirage_no_eligible_title: "No eligible members",
    tirage_no_eligible_msg: "All members up to date with their contributions for this round have already benefited from a draw.",
    sign_payout_1: "Confirm payout of {amount} F to {name}? (Signature 1/2)",
    sign_payout_2: "Confirm final payout (Signature 2/2)?",
    reminder_default_msg: "This is a reminder for your Nataal contribution. Please regularize your situation.",
    // Topbar page titles
    page_home: "Dashboard", page_finances: "Finances", page_members: "Members",
    page_tontines: "Tontines", page_notifications: "Notifications",
    page_rappels: "Send a reminder", page_settings: "Settings",
    page_profile: "My Profile", page_tirage: "Monthly Draw",
    page_privacy: "Privacy", page_cgu: "Terms", page_faq: "FAQ",
    // Join tontine prompt
    no_tontine_title: "You haven't joined a tontine yet",
    no_tontine_sub: "Enter the 6-character invitation code shared by your manager.",
    no_tontine_btn: "Join a tontine",
    // LoanItem
    loan_status_pending: "Pending", loan_status_approved: "Approved", loan_status_current: "In progress", loan_status_repaid: "Repaid", loan_status_rejected: "Rejected",
    loan_cancel: "Cancel", loan_processing: "Processing...", loan_confirm_reject: "Confirm rejection", loan_confirm_signature: "Confirm signature",
    loan_member: "Member", loan_no_motif: "No reason", loan_already_signed: "✓ Already signed", loan_sign_step1: "✍ Sign (1/2)", loan_sign_step2: "✍ Confirm (2/2)",
    loan_reject_btn: "Reject", loan_capital: "Capital", loan_total_interests: "Total with interest (10%)", loan_rejected_title: "Request rejected",
    loan_rejected_msg: "This loan request has been refused by the managers.", loan_pending_title: "Awaiting validation",
    loan_pending_msg: "2 manager signatures required ({count}/2 received)", loan_loading_schedule: "Loading schedule...",
    loan_schedule_title: "Repayment schedule", loan_paid: "PAID", loan_to_pay: "TO PAY", loan_collect_btn: "Collect",
    loan_balance_due: "Balance due", loan_collect_amount: "Collect {amount} F", loan_confirm_collect: "Confirm collection of the installment of {amount} F?",
    // SpinWheel
    spin_winner_congrats: "🎉 Congratulations {name}! You have been drawn for the {month} round of Nataal Tontine. Amount: {amount} FCFA. Contact the administrator for payment. Good luck! 🤝",
    spin_winner_label: "Draw Beneficiary", spin_amount_month: "Amount — {month}", spin_send_sms: "📱 Send an SMS",
    spin_no_phone: "No phone number recorded", spin_close: "Close", spin_spinning: "The wheel is spinning…",
    spin_launch: "🎲 Start the draw", spin_eligible_count: "{count} eligible participant{s}",
    // Logout confirmation
    logout_confirm_title: "Sign out?",
    logout_confirm_msg: "You will be redirected to the login page.",
    logout_confirm_yes: "Sign out",
    logout_confirm_no: "Cancel",
    // Finances filters
    all: "All", pending: "Pending", approved: "Approved", repaid: "Repaid", rejected: "Rejected",
    export: "Export",
    // Profile
    edit_profile: "Edit profile", change_password: "Change password",
    // Tontines
    all_tontines: "All Tontines", invite_code: "Invitation code", copy: "Copy", join: "Join", evaluation: "Evaluation",
    status: "Status", progression: "Progression",
    tontine_intro_gerant: "Configuration, join or evaluation.",
    tontine_intro_membre: "Join a tontine or view evaluation.",
    copy_success: "Code copied.", invite_code_sub: "Share this code (6 chars) to invite a member.",
    available_tontines: "Available Tontines", share_with_members: "To share with members",
    // Landing Page
    landing_hero_badge: "Next-generation management system",
    landing_hero_title: "Lead your Tontine with absolute clarity.",
    landing_hero_sub: "The premium solution to manage your contributions, rounds and loans. Simplify your collective savings with a professional and transparent interface.",
    landing_cta_start: "Start now",
    landing_cta_view: "View my tontine",
    landing_cta_note: "Over 500 active members already in Senegal.",
    landing_divider_text: "Excellence & Trust",
    landing_features_label: "Our pillars",
    landing_feat1_title: "Total Security",
    landing_feat1_text: "Your funds and data are protected by end-to-end encryption and a multi-criteria validation system.",
    landing_feat2_title: "Random Draw",
    landing_feat2_text: "A transparent and fair algorithm to designate monthly beneficiaries live.",
    landing_feat3_title: "Easy Loans",
    landing_feat3_text: "Access internal credit solutions with rapid validation by tontine managers.",
    landing_stats_label: "In a few numbers",
    landing_stat1_label: "CFA Collected monthly",
    landing_stat2_label: "Repayment rate",
    landing_stat3_label: "Dashboard access",
    landing_footer_copy: "© 2026 Nataal Group. All rights reserved.",
    // Auth
    login_title: "Login",
    login_subtitle: "Access your Tontine Nataal space",
    login_email_label: "Professional Email",
    login_pass_label: "Password",
    login_btn: "Login",
    login_loading: "Logging in...",
    login_no_account: "Not a member yet?",
    login_create_account: "Create account",
    register_title: "Register",
    register_subtitle: "Create your Tontine Nataal account",
    register_name_label: "Full Name",
    register_btn: "Create my account",
    register_loading: "Creating...",
    register_already_member: "Already a member?",
    back: "Back",
    // Dashboard missing
    per_member_month: "Per member / month",
    total_personal: "Total personal",
    global_progress: "Global progress",
    recent_activity_log: "Recent activity log",
    loan_rate: "Global payment rate",
    all_read: "Mark all read",
    unread: "Unread",
    // Supplementary
    members_list: "Members list",
    paid: "Paid",
    edit: "Edit",
    confirm_action: "Confirm action",
    old_password: "Old password",
    new_password: "New password",
    validate_change: "Validate change",
    turn: "Turn",
    fill_all_fields: "Please fill all fields",
    saving: "Saving...",
    photo: "Photo",
    remove_photo: "Remove photo",
    tirage_title: "Monthly Draw",
    cycle_in_progress: "Cycle in progress",
    members_served: "members served",
    no_security_log: "No security logs found",
    audit_title: "Audit & Security Log",
    loading_history: "Loading history...",
    user: "User",
    details: "Details",
    amount: "Amount",
    invalid_amount: "Please enter a valid amount",
    tirage_confirm_msg: "Start the monthly draw?",
    payout_confirm_msg: "Confirm sending money?",
    irreversible_action: "This action is irreversible.",
    all_beneficiaries_served: "All members have served! New cycle coming soon.",
    disbursement: "Disbursement",
    confirm_reminder_all: "Send a reminder email to all members waiting for payment?",
    tontine_name_placeholder: "Ex: Friends Tontine",
    tontine_desc_placeholder: "Describe your tontine...",
    tontine_intro_gerant: "Setup, join or evaluation.",
    tontine_intro_membre: "Join a tontine or view evaluation.",
    copy_success: "Code copied.",
    copy: "Copy",
    invite_code: "Invitation Code",
    invite_code_sub: "Share this code (6 characters) to invite a member.",
    join: "Join",
    error_occurred: "An error occurred",
    refresh: "Refresh",
    beneficiary_banner_title: "You are the beneficiary of the month!",
    amount_sent: "sent",
    amount_will_be_sent: "will be sent to you",
    status_received: "RECEIVED",
    status_pending: "PENDING",
    sign_payout_1: "Validate your signature (1/2) to payout {amount} F to {name}?",
    sign_payout_2: "Confirm final signature (2/2) and close this round?",
    tirage_congrats: "🏆 Congratulations {name}! You are the winner of the {month} draw.",
    tirage_error: "Draw error: ",
    tirage_modal_title: "🎲 Draw — ",
    tirage_no_eligible_title: "No eligible participants",
    tirage_no_eligible_msg: "All members have already received their turn, or none have contributed this month.",
    // TiragePage
    tirage_current_month: "CURRENT MONTH DRAW",
    tirage_beneficiary_selected: "Selected beneficiary",
    tirage_amount: "Amount",
    tirage_confirm_send: "Confirm money transfer",
    tirage_sending: "Sending...",
    tirage_sent_on: "Money sent on",
    tirage_new_month: "NEW MONTHLY DRAW",
    tirage_amount_label: "AMOUNT TO SEND (F CFA)",
    tirage_info: "The system will randomly select a participant who has not yet benefited.",
    reminder_default_msg: "⚠️ Reminder: your contribution is pending. Please settle as soon as possible.",
    faq_title: "Frequently Asked Questions",
    faq_q1: "How to join a tontine?",
    faq_a1: "Use the 6-digit code shared by your manager in the 'Join' section.",
    faq_q2: "How does the draw work?",
    faq_a2: "The draw is performed randomly by the system among members who have contributed.",
    faq_q3: "Is it secure?",
    faq_a3: "Yes, all transactions and data are encrypted and protected.",
    tirage_launching: "Drawing in progress...",
    tirage_launch_btn: "Start the monthly draw",
    tirage_history: "DRAW HISTORY",
    tirage_sent_status: "✓ Sent",
    tirage_waiting_status: "⏳ Pending",
    // SettingsPage
    settings_new_pool: "New pool",
    settings_title_label: "Title",
    settings_description_label: "Description",
    settings_description_optional: "(Optional)",
    settings_amount_per_place: "Amount per place",
    settings_frequency_label: "Frequency",
    settings_fees_label: "Management fees",
    settings_freq_monthly: "Per month",
    settings_freq_weekly: "Per week",
    settings_freq_daily: "Per day",
    settings_nb_places: "No. of places",
    settings_start_date: "Start date",
    settings_total_pool: "Total pool",
    settings_saving: "Saving...",
    settings_saved: "✅ Saved!",
    settings_save_btn: "Save changes",
    settings_title_required: "Title is required",
    settings_freq_value_monthly: "Monthly",
    settings_freq_value_weekly: "Weekly",
    settings_freq_value_daily: "Daily",
    // Notifications
    notif_center: "Notification center",
    notif_elements: "item(s)",
    notif_unread: "Unread",
    notif_all: "All",
    notif_mark_all_read: "Mark all read",
    notif_loading: "Loading…",
    notif_empty: "No notifications.",
    // Reminders
    reminder_title: "Payment reminders",
    reminder_subtitle: "In-app notifications for pending members",
    reminder_all: "All overdue members",
    reminder_select: "Specific selection",
    reminder_pending_members: "Pending members",
    reminder_message_label: "Reminder message",
    reminder_sending: "Sending...",
    reminder_send_btn: "Send reminders now",
    // Modals
    modal_photo_label: "Profile photo",
    modal_photo_hint: "Click the icon to change.",
    modal_photo_remove: "✕ Remove photo",
    modal_photo_remove_short: "✕ Remove",
    modal_photo_optional: "Optional • JPG, PNG • Max 3 MB",
    modal_nom_label: "Last name",
    modal_prenom_label: "First name",
    modal_email_label: "Email Address",
    modal_email_label_short: "Email",
    modal_email_required: "Email *",
    modal_nom_required: "Last name *",
    modal_telephone_label: "Phone",
    modal_password_temp: "Temporary password *",
    modal_password_placeholder: "Password",
    modal_edit_member_title: "Edit member",
    modal_save_changes: "Save changes",
    modal_saving: "Saving...",
    modal_creating: "Creating...",
    modal_create_member_btn: "Create member",
    modal_confirm_title: "Confirmation",
    modal_delete_confirm: "Delete this member?",
    modal_delete_msg: "This action is irreversible. Data for",
    modal_delete_msg2: "(transactions, rounds) will be permanently deleted.",
    modal_cancel: "Cancel",
    modal_delete_btn: "Delete",
    modal_deleting: "Deleting...",
    modal_loan_title: "Request a loan",
    modal_loan_amount_label: "Desired amount (F CFA)",
    modal_loan_reason_label: "Reason for request",
    modal_loan_warning: "This request requires validation by two managers.",
    modal_loan_submitting: "Submitting...",
    modal_loan_submit_btn: "Submit request",
    modal_cotiser_confirm: "Confirm payment",
    modal_cotiser_processing: "Processing...",
    modal_password_changed: "Password changed.",
    // Finances hardcoded
    no_data: "No data",
    no_activity_period: "No activity recorded for this period.",
    no_transaction: "No transactions available.",
    loan_none: "No loans recorded yet",
    loan_none_filtered: "No loans",
    loan_create_request: "Create a loan request",
    loan_total_borrowed: "TOTAL BORROWED",
    loan_pending_count: "PENDING",
    loan_repaid_count: "REPAID",
    // MembresPage batch
    batch_selected: "member(s) selected for contribution",
    // TontinesPage etat
    tontine_progression_label: "Progression",
    tontine_tour_label: "Round",
    tontine_code_invalid: "Invalid code.",
    tontine_6chars: "(6 characters)",
    // ProfilPage
    profile_click_to_modify: "Click the icon to change.",
    email_label: "Email",
    // LandingPage divider
    landing_divider_text_inline: "Excellence & Trust",
    email_placeholder: "your@email.com",
    name_placeholder: "John Doe",
    // ParametresPage
    password_changed_msg: "Password changed.",
    privacy_title: "Privacy Policy",
    privacy_intro: "At Nataal, we place capital importance on protecting your data. This policy details how we collect and use your information.",
    privacy_h1: "1. Data Collection",
    privacy_p1: "We collect your names, emails, phone numbers and transaction histories to ensure the smooth running of the tontine.",
    privacy_h2: "2. Usage",
    privacy_p2: "Your data is used solely for managing tontine rounds, loans and reminder notifications.",
    cgu_title: "Terms of Service",
    cgu_intro: "Using Nataal implies full acceptance of these terms.",
    cgu_h1: "1. Member Commitment",
    cgu_p1: "Each member agrees to contribute on time according to the frequency defined by the manager.",
    cgu_h2: "2. Penalties",
    cgu_p2: "Any delay may result in automatic penalties defined in the tontine settings.",
    placeholder_phone: "+221 ...",
    placeholder_subject: "Subject...",
    placeholder_message: "Write your message here...",
    placeholder_loan_reason: "Ex: Tuition fees, Emergency...",
    tontine_premium: "Premium Tontine",
  },
  wo: {
    home: "Keur gui", finances: "Khaliss", members: "Mbok yi", settings: "Réglages", profile: "Profil",
    welcome_message: "Nanga def",
    welcome_subtitle: "Li moy li dadié tay: cotisation yi, tour bi nek ak li ci kanam.",
    beneficiary_banner_title: "Yaw ya bénéficier weer wi !",
    beneficiary_banner_received: "yonénagn ko", beneficiary_banner_waiting: "dinagn ko yone",
    update_data: "Yéssal nani yi", active_cycle: "Cycle bi nek", current_tour: "Tour",
    next_beneficiary: "Bénéficiaire bi ci kanam", total_pool: "Cagnotte bi dadié",
    cycle_progression: "Avancement cycle bi",
    pay_cotisation_wave: "Feye sama cotisation (Wave)", pay_cotisation_orange: "Feye (Orange Money)",
    target_cotisation: "Cotisation bi", amount_contributed: "Li feyu",
    next_tour: "Tour bi ci kanam", estimated_order: "Ordre bi",
    sign_for_payout: "Signél décaissement bi", confirm_payout_msg: "Nangu sa signature",
    signed_payout: "Signature enregistrée", make_loan_request: "Demander prêt",
    recent_activity: "Opération yi moudié", no_recent_activity: "Amoul dara li ni.",
    cotisation: "Cotisation", penalty: "Pénalité", loan: "Prêt", draw: "Tirage",
    loading: "Xaaral touti...", refreshing: "Yéssal...",
    financial_performance: "Performance khaliss", real_time: "Temps réel",
    dashboard_overview: "Vue d'ensemble", loans: "Prêts",
    finance_intro: "Sétal indicateur yi, gérer flux yi ak guéné rapport yi.",
    cotisations_today: "Cotisation yi tay", pending_penalties: "Pénalité yi nek",
    active_loans: "Prêt yi nek", top_contributors: "Mbok yi eup li gni diokh",
    cycle_summary: "Résumé cycle bi", total_collected: "Li dadié",
    loan_repayment_rate: "Taux cotisation", real_time_flow: "Flux bi en temps réel",
    latest_transactions: "Transaction yi moudié",
    add_member: "Yok mbok", start_tirage: "Lancer tirage bi",
    send_reminders: "Yone rappel", paid_members: "Mbok yi fey",
    no_member_found: "Amoul mbok fi.", apply_penalty: "Déf pénalité",
    tontine_settings: "Parametou Tontine bi", tontine_name: "Tourou Tontine bi",
    save_changes: "Enregistrer",
    logout: "Guen", change_language: "Changer langue bi",
    dark_mode: "Mode sombre", light_mode: "Mode clair", language_select: "Tannal sa lak",
    // Navigation sidebar
    nav_home: "Keur gui", nav_finances: "Khaliss", nav_members: "Mbok yi",
    nav_tontines: "Tontines", nav_tirage: "Tirage", nav_notifications: "Xibaar yi",
    nav_rappels: "Rappel yi", nav_settings: "Réglages",
    nav_group_main: "Li moy", nav_group_manage: "Gérer",
    system_active: "Système actif",
    role_admin: "Gérant · Admin",
    role_member: "Mbok bi",
    // Topbar page titles
    page_home: "Keur gui", page_finances: "Khaliss", page_members: "Mbok yi",
    page_tontines: "Tontines", page_notifications: "Xibaar yi",
    page_rappels: "Yone rappel", page_settings: "Réglages",
    page_profile: "Sama Profil", page_tirage: "Tirage bi",
    page_privacy: "Confidentialité", page_cgu: "CGU", page_faq: "FAQ",
    // Join tontine prompt
    no_tontine_title: "Danga fey rejoindre tontine",
    no_tontine_sub: "Dugal code bi (6 caractères) li sa gérant joxe.",
    no_tontine_btn: "Rejoindre une tontine",
    // LoanItem
    loan_status_pending: "Mu ngi xar", loan_status_approved: "Dëgël na", loan_status_current: "Mu ngi dox", loan_status_repaid: "Feyy na", loan_status_rejected: "Bagn na",
    loan_cancel: "Annuler", loan_processing: "Mu ngi dox...", loan_confirm_reject: "Dëgël bagn bi", loan_confirm_signature: "Dëgël signature bi",
    loan_member: "Mbok bi", loan_no_motif: "Amoul motif", loan_already_signed: "✓ Signer na", loan_sign_step1: "✍ Signer (1/2)", loan_sign_step2: "✍ Dëgël (2/2)",
    loan_reject_btn: "Bagn", loan_capital: "Capital", loan_total_interests: "Mbepp ak intérêts (10%)", loan_rejected_title: "Demande bi bagn na",
    loan_rejected_msg: "Demande prêt bi gérant yi bagn na gnu ko.", loan_pending_title: "Gungui xar dëgël bi",
    loan_pending_msg: "Ladj na 2 signatures gérant ({count}/2 jot na)", loan_loading_schedule: "Mu ngi xar échéancier bi...",
    loan_schedule_title: "Échéancier feyy bi", loan_paid: "FEYY NA", loan_to_pay: "WAAR NA FEYY", loan_collect_btn: "Encaisser",
    loan_balance_due: "Li dess ci feyy bi", loan_collect_amount: "Encaisser {amount} F", loan_confirm_collect: "Dëgël encaisser échéance bu {amount} F ?",
    // SpinWheel
    spin_winner_congrats: "🎉 Félicitations {name} ! Yaw ya gagné tirage bu {month} bi ci Tontine Nataal. Montant bi : {amount} FCFA. Waxal ak gérant bi ngir feyy bi. Bonne chance ! 🤝",
    spin_winner_label: "Kiy gagné tirage bi", spin_amount_month: "Montant — {month}", spin_send_sms: "📱 Yoneel SMS",
    spin_no_phone: "Amoul numéro téléphone", spin_close: "Ubbi", spin_spinning: "Roue bi mu ngi tourné…",
    spin_launch: "🎲 Lancer tirage bi", spin_eligible_count: "{count} mbok mu éligible",
    // Logout confirmation
    logout_confirm_title: "Guen ?",
    logout_confirm_msg: "Dinaga dem ci page connexion bi.",
    logout_confirm_yes: "Guen",
    logout_confirm_no: "Dëgël",
    // Roles
    role_admin: "Gérant",
    role_member: "Mbok",
    // Finances filters
    all: "Mbepp", pending: "Xaaral", approved: "Nangu", repaid: "Feyu", rejected: "Bagn",
    export: "Guéné",
    // Profile
    edit_profile: "Soppi profil bi", change_password: "Soppi mot de passe bi",
    // Tontines
    all_tontines: "Mbépp tontine", invite_code: "Code bi", copy: "Copier", join: "Rejoindre", evaluation: "Évaluation",
    status: "Statut", progression: "Progression",
    tontine_intro_gerant: "Mbinde, rejoindre wala évaluation.",
    tontine_intro_membre: "Rejoindre tontine wala séét évaluation.",
    copy_success: "Code bi copier na.", invite_code_sub: "Yonél code bi sa mbok yi.",
    available_tontines: "Tontine yi Dawal", share_with_members: "Bënn mbok yi",
    // Landing Page
    landing_hero_badge: "Système bu yees bi",
    landing_hero_title: "Doxalal sa Tontine ak leer gu mat sëkk.",
    landing_hero_sub: "Solution premium bi gërëm pour géré sa cotisation yi, tour yi ak prêt yi. Yombalal sa épargne collective ak interface professionnelle ak transparente.",
    landing_cta_start: "Tambali légui",
    landing_cta_view: "Sétal sama tontine",
    landing_cta_note: "Eup na 500 mbok yi dawal fi Sénégal.",
    landing_divider_text: "Excellence ak Confiance",
    landing_features_label: "Souniou piliers",
    landing_feat1_title: "Sécurité bu mat",
    landing_feat1_text: "Sa xaliss ak sa mbir yi gnu ngi sécurisé ak cryptage bu mat ak système de validation bu am doole.",
    landing_feat2_title: "Tirage bu amoul sori",
    landing_feat2_text: "Algorithme bu leer ak bu équitable pour tann bénéficiaires yi weer wu nekk en direct.",
    landing_feat3_title: "Prêt yi yomb",
    landing_feat3_text: "Amal accès ci solution de crédit yi biir tontine bi ak validation bu gaw li gérant yi di def.",
    landing_stats_label: "Ci yenn chiffres yi",
    landing_stat1_label: "CFA yi dadié weer wu nekk",
    landing_stat2_label: "Taux de remboursement bi",
    landing_stat3_label: "Accès ci tableau de bord bi",
    landing_footer_copy: "© 2026 Nataal Group. Mbepp droit yi gnu ngi gardé.",
    // Auth
    login_title: "Connexion",
    login_subtitle: "Dugal ci sa espace Tontine Nataal",
    login_email_label: "Email bi",
    login_pass_label: "Mot de passe bi",
    login_btn: "Dugal",
    login_loading: "Mu ngi duggal...",
    login_no_account: "Mbokulon ba légui?",
    login_create_account: "Sos sa compte",
    register_title: "Inscription",
    register_subtitle: "Sosal sa compte Tontine Nataal",
    register_name_label: "Sa tour ak sa santa",
    register_btn: "Sosal sama compte",
    register_loading: "Mu ngi sos...",
    register_already_member: "Mbok nga ba paré?",
    back: "Delou",
    // Dashboard missing
    per_member_month: "Ci mbok mu nekk / weer",
    total_personal: "Li mbepp fey",
    global_progress: "Avancement bi",
    recent_activity_log: "Journal bi moudié",
    loan_rate: "Taux de paiement bi",
    all_read: "Lire mbepp",
    unread: "Lire wugn ko",
    // Supplementary
    members_list: "Liste mbok yi",
    paid: "Fey na",
    edit: "Soppi",
    confirm_action: "Dëgël",
    status_received: "Jot nako",
    status_pending: "Mu ngi xar",
    tirage_congrats: "Félicitations {name} ! Yaw ya gagné tirage bu {month} bi. Cagnotte : {amount} FCFA.",
    tirage_modal_title: "Tirage au sort - ",
    tirage_no_eligible_title: "Amoul mbok mu éligible",
    tirage_no_eligible_msg: "Mbepp mbok yi feyy cotisation weer wi gagné nagn tirage ba paré.",
    sign_payout_1: "Dëgël décaissement bu {amount} F pour {name} ? (Signature 1/2)",
    sign_payout_2: "Dëgël décaissement final bi (Signature 2/2) ?",
    reminder_default_msg: "Li moy rappel pour sa cotisation Nataal. Bo ko feyé gnu dëgël ko.",
    old_password: "Mot de passe bu yéne",
    new_password: "Mot de passe bu yées",
    validate_change: "Dëgël soppi bi",
    turn: "Tour",
    fill_all_fields: "Dugalal fép fép",
    saving: "Denc...",
    photo: "Nataal",
    remove_photo: "Dindi nataal bi",
    tirage_title: "Tirage weer wi",
    cycle_in_progress: "Cycle bi nek ni",
    members_served: "mbok yi jot",
    no_security_log: "Amoul journal sécurité",
    audit_title: "Journal Audit & Sécurité",
    loading_history: "Mu ngi xaaral historique...",
    user: "Utilisateur",
    details: "Détails",
    amount: "Montant",
    invalid_amount: "Dugalal montant bu baax",
    tirage_confirm_msg: "Lancer tirage bi ?",
    payout_confirm_msg: "Yoné xaliss bi ?",
    irreversible_action: "Action bi meunul dadié.",
    all_beneficiaries_served: "Mbok mbepp jot na gnu ! Cycle bu yees mu ngi ñëw.",
    disbursement: "Décaissement",
    confirm_reminder_all: "Yoné email rappel ci mbok yi mbepp xaaral ?",
    tontine_name_placeholder: "Ex: Tontine ay xarit",
    tontine_desc_placeholder: "Xibaari sa tontine...",
    tontine_intro_gerant: "Configuration, bok wala évaluation.",
    tontine_intro_membre: "Bok ci tontine wala guiss évaluation.",
    copy_success: "Code copié.",
    copy: "Copier",
    invite_code: "Code d'invitation",
    invite_code_sub: "Partageël code bi (6 caractères) ngir bok mbok.",
    join: "Bok",
    error_occurred: "Erreur amna",
    refresh: "Rafraîchir",
    beneficiary_banner_title: "Yaw yaay gagné bi weer !",
    amount_sent: "yoné na",
    amount_will_be_sent: "dina gnu la yoné",
    status_received: "JOT NA",
    status_pending: "XAARAL",
    sign_payout_1: "Dëgël sa signature (1/2) ngir yoné {amount} F ci {name} ?",
    sign_payout_2: "Dëgël signature bu mujj bi (2/2) ?",
    // TiragePage
    tirage_current_month: "TIRAGE BI WAAR WI",
    tirage_beneficiary_selected: "Bénéficiaire bi tannékh",
    tirage_amount: "Montant",
    tirage_confirm_send: "Yoné xaliss bi",
    tirage_sending: "Mu ngi yoné...",
    tirage_sent_on: "Xaliss yonéna",
    tirage_new_month: "TIRAGE YEES BI",
    tirage_amount_label: "MONTANT BI (F CFA)",
    tirage_info: "Système bi dinaa tann mbok benn bu amul koo jot.",
    reminder_default_msg: "⚠️ Rappel: sa cotisation mu ngi xaar. Dieureudieuf nga feyy ko légui.",
    faq_title: "FAQ - Ladj yi mbepp",
    faq_q1: "Naka la gnu bokké ci tontine ?",
    faq_a1: "Jëfëlë code 6 chiffres bi sa gérant yoné ci section 'Bok'.",
    faq_q2: "Naka la tirage bi di démé ?",
    faq_a2: "System bi dina tann aléatoirement ci mbok yi feyy weer wi.",
    faq_q3: "Dafa sécurisé ?",
    faq_a3: "Waaw, mbepp transaction ak données gnu ngi leen chiffré te protéger.",
    tirage_launching: "Tirage bi nek...",
    tirage_launch_btn: "Lancer tirage bi",
    tirage_history: "HISTORIQUE TIRAGE YI",
    tirage_sent_status: "✓ Yonéna",
    tirage_waiting_status: "⏳ Xaaral",
    // SettingsPage
    settings_new_pool: "Cagnotte yees",
    settings_title_label: "Tourou",
    settings_description_label: "Xibaari",
    settings_description_optional: "(Amul solo)",
    settings_amount_per_place: "Montant ci këm këm",
    settings_frequency_label: "Fréquence",
    settings_fees_label: "Frais gestion",
    settings_freq_monthly: "Ci weer wu nekk",
    settings_freq_weekly: "Ci ayubéses wi",
    settings_freq_daily: "Ci bés bu nekk",
    settings_nb_places: "Nombre places",
    settings_start_date: "Dateu tambali",
    settings_total_pool: "Cagnotte mbepp",
    settings_saving: "Denc...",
    settings_saved: "✅ Dencéna!",
    settings_save_btn: "Enregistrer soppi yi",
    settings_title_required: "Tourou bi dafa doon.",
    settings_freq_value_monthly: "Mensuelle",
    settings_freq_value_weekly: "Hebdo",
    settings_freq_value_daily: "Quotidienne",
    // Notifications
    notif_center: "Centre notifications yi",
    notif_elements: "élément(s)",
    notif_unread: "Jéemulna",
    notif_all: "Mbepp",
    notif_mark_all_read: "Jéem mbepp",
    notif_loading: "Xaaral…",
    notif_empty: "Amoul notification.",
    // Reminders
    reminder_title: "Rappel feyyi",
    reminder_subtitle: "Notifications ci mbok yi xaaral",
    reminder_all: "Mbok yi mbepp xaaral",
    reminder_select: "Tann précis",
    reminder_pending_members: "Mbok yi xaaral",
    reminder_message_label: "Message rappel bi",
    reminder_sending: "Yonél...",
    reminder_send_btn: "Yonél rappel yi légui",
    // Modals
    modal_photo_label: "Nataal profil bi",
    modal_photo_hint: "Tekki nataal bi ngir soppi.",
    modal_photo_remove: "✕ Dindi nataal bi",
    modal_photo_remove_short: "✕ Dindi",
    modal_photo_optional: "Amul solo • JPG, PNG • Max 3 MB",
    modal_nom_label: "Santa",
    modal_prenom_label: "Tour",
    modal_email_label: "Adresse Email",
    modal_email_label_short: "Email",
    modal_email_required: "Email *",
    modal_nom_required: "Santa *",
    modal_telephone_label: "Téléphone",
    modal_password_temp: "Mot de passe provisoire *",
    modal_password_placeholder: "Mot de passe",
    modal_edit_member_title: "Soppi mbok",
    modal_save_changes: "Enregistrer soppi yi",
    modal_saving: "Denc...",
    modal_creating: "Mu ngi sos...",
    modal_create_member_btn: "Sos mbok bi",
    modal_confirm_title: "Dëgël",
    modal_delete_confirm: "Dindi mbok bi ?",
    modal_delete_msg: "Action bi meunul dadié. Données",
    modal_delete_msg2: "(transactions, tours) dina démél.",
    modal_cancel: "Dëgël",
    modal_delete_btn: "Dindi",
    modal_deleting: "Mu ngi dindi...",
    modal_loan_title: "Demand prêt",
    modal_loan_amount_label: "Montant bi (F CFA)",
    modal_loan_reason_label: "Motif bi",
    modal_loan_warning: "Demande bi dafa soxor validation ji gérant yi ñar.",
    modal_loan_submitting: "Mu ngi yoné...",
    modal_loan_submit_btn: "Yoné demande bi",
    modal_cotiser_confirm: "Dëgël feyyi bi",
    modal_cotiser_processing: "Mu ngi traiter...",
    modal_password_changed: "Mot de passe soppi na.",
    // Finances hardcoded
    no_data: "Amoul données",
    no_activity_period: "Amoul activité ci période bi.",
    no_transaction: "Amoul transaction.",
    loan_none: "Amoul prêt ba légui",
    loan_none_filtered: "Amoul prêt",
    loan_create_request: "Sos demande prêt",
    loan_total_borrowed: "MBEPP LI EM",
    loan_pending_count: "XAARAL",
    loan_repaid_count: "FEYU",
    // MembresPage batch
    batch_selected: "mbok(s) tannékh pour cotisation",
    // TontinesPage etat
    tontine_progression_label: "Avancement",
    tontine_tour_label: "Tour",
    tontine_code_invalid: "Code bu baax.",
    tontine_6chars: "(6 caractères)",
    // ProfilPage
    profile_click_to_modify: "Tekki nataal bi ngir soppi.",
    email_label: "Email",
    // LandingPage divider
    landing_divider_text_inline: "Excellence ak Confiance",
    email_placeholder: "sa@email.com",
    name_placeholder: "Moussa Diop",
    // ParametresPage
    password_changed_msg: "Mot de passe soppi na.",
    tirage_congrats: "🏆 Félicitations {name} ! Yaw ya gagné tirage bu {month} bi.",
    tirage_error: "Erreur tirage : ",
    tirage_modal_title: "🎲 Tirage — ",
    tirage_no_eligible_title: "Amoul mbok bu éligible",
    tirage_no_eligible_msg: "Mbok yi mbepp jot na gnu seen tour, wala amoul koo feyy weer wi.",
    privacy_title: "Xibaari confidentialité bi",
    privacy_intro: "Ci Nataal, dencu sa données dafa am solo lool. Xibaari bi dina la wax naka la gnu di dencé ak naka la gnu di jëfëndiko sa xibaari.",
    privacy_h1: "1. Dencu données yi",
    privacy_p1: "Gnu ngi denc sa tour, sa email, sa numéro téléphone ak historique sa transactions yi ngir tontine bi dox bu baax.",
    privacy_h2: "2. Jëfëndiko",
    privacy_p2: "Sa données yi gnu ngi leen di jëfëndiko rek ngir gérer tourou tontine yi, prêt yi ak notifications rappel yi.",
    cgu_title: "Conditions Générales d'Utilisation",
    cgu_intro: "Bok ci Nataal dafa ladj nga dëgël mbepp conditions yi.",
    cgu_h1: "1. Engagement mbok yi",
    cgu_p1: "Mbok mu nekk dafa waar feyy ci waxtu wi gérant bi tann.",
    cgu_h2: "2. Pénalités",
    cgu_p2: "Mbepp retard mën na ladj pénalités automatiques yi nek ci paramètres tontine bi.",
    placeholder_phone: "+221 ...",
    placeholder_subject: "Sujet...",
    placeholder_message: "Bindal sa message fi...",
    placeholder_loan_reason: "Ex: Scolarité, Urgence...",
    tontine_premium: "Tontine premium",
  }
};

export const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('tontine-lang') || 'fr');

  useEffect(() => {
    localStorage.setItem('tontine-lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['fr']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
